application: appname
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static/
  static_dir: algby/static


- url: .*
  script: app.app

builtins:
- django_wsgi: on
- remote_api: on


env_variables:
  DJANGO_SETTINGS_MODULE: 'algby.settings'


